### ISSUE TITLE
Bitcode

### ISSUE THREAD

**Issue by iwheelbuy** [CappasityTech/iOSFramework#2]
> ld: bitcode bundle could not be generated because '...Cappasity.framework/Cappasity' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '...Cappasity.framework/Cappasity' for architecture armv7

**Comment by iwheelbuy** [comment]
https://blog.noveogroup.ru/2018/01/kak-delali-ios-framework/

**Comment by AlexanderCappasity** [comment]
Thank you for your feedback.
Please check our latest release 0.4.8.
[Releases](https://github.com/CappasityTech/iOSFramework/releases)
